# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 5
semi: true
singleQuote: true
printWidth: 120
endOfLine: 'crlf'
jsxSingleQuote: true
plugins: ['prettier-plugin-tailwindcss', 'prettier-plugin-organize-imports', 'prettier-plugin-packagejson']
